theme = "catppuccin_mocha"

[editor]
mouse = false
bufferline = "always"
rulers = [88]

[editor.search]
smart-case = true
wrap-around = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
X = ["extend_line_up", "extend_to_line_bounds"]
";" = "flip_selections"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
H = "goto_previous_buffer"
L = "goto_next_buffer"

[keys.normal.space]
w.c = ":buffer-close"
w.space = ":write"

[keys.normal.space.l]
j = "goto_next_diag"
k = "goto_prev_diag"
f = "goto_next_function"
F = "goto_prev_function"
t = "goto_next_class"
T = "goto_prev_class"

[keys.select]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
";" = "flip_selections"
