theme = "catppuccin_mocha"

[editor]
mouse = false
line-number = "relative"

[editor.search]
smart-case = true
wrap-around = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
X = ["extend_line_up", "extend_to_line_bounds"]
";" = "flip_selections"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
"ret" = "goto_word"

[keys.normal.space]
w.c = ":buffer-close"
w.space = ":write"
q.q = ":quit-all"

[keys.select]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
";" = "flip_selections"
X = ["extend_line_up", "extend_to_line_bounds"]
