[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]
auto-format = true

[[language]]
name = "solidity"
language-servers = ["solidity-ls-nomicfoundation"]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
config.python.analysis.typeCheckingMode = "off"

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.solidity-ls-nomicfoundation]
command = "nomicfoundation-solidity-language-server"
args = ["--stdio"]
