[[language]]
name = "python"
auto-format = true
language-servers = [ "pyright", "ruff-lsp" ]

[[language]]
name = "solidity"
language-servers = ["solidity-ls-nomicfoundation"]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
config.python.analysis.typeCheckingMode = "off"

[language-server.ruff-lsp]
command = "ruff-lsp"
args = []
config = {}

[language-server.solidity-ls-nomicfoundation]
command = "nomicfoundation-solidity-language-server"
args = ["--stdio"]
